In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\harsh\Documents\data Analyst Projects\complex_phone_data\data_scraping\final_ds.csv")

In [3]:
df.sample(2)

,brand_name,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
2451,Itel it2190,NaN,NaN,0.3 MP Rear Camera,NaN,1000 mAh | 2W,1.8 inches (4.57 cm) | TFT,NaN,"₹1,125"
2170,Infinix Note 40 Pro Plus 5G,MediaTek Dimensity 7020,12 GB RAM | 256 GB Storage,108 MP + 2 MP + 2 MP Rear Camera,32 MP Front Camera,4600 mAh | 100W Fast Charging,6.78 inches (17.22 cm) | Flexible AMOLED,NaN,"₹24,999"

## Data Assessing

#### mannual assessing

`brand name`
- data in row 1177 is missing

`processor`
- row no 1494 has nm info in processor

`storage`
- ram and rom both are present in same col /
- row no 62 have type of storage info
- row 2307, 2849, 2952, 2958, 2981, 2982, 2983, 2985, 2986, 2987, 2989, 2993, 2994, 2995, 2996, 2998, 2999, 3000, 4128 , 4211, 4306, 4310,315, 4316, 4322, 4331, 4332, 4334, 4336, 4340, 4342, 4352, 4357, 4358, 4359, 4377, 4379, 4383, 4387, 4389, 4393, 4396, 4398, 4400, 4402, 4403, 4404, 4406, 4407, 4408, 4409, 4412, 4413, 4414, 4415, 4417, 4422, 4423, 4424, 4425, 4426, 4427, 4431, 4450, 4452, 4466, 4467, 4468 have only storage

- row 4025, 4086, 4183, 4204, 4233, 4297, 4305, 4314,
  4420, 4447, 4448, 4456, 4558 have only ram

`battery`
- this col can be split into two 1st battery and 2nd charging speed
- at some places it's directly mentioned 3000 mAh Fast Charging, 3300 mAh Quick Charging, 5000 mAh | 10W Fast Charging

`display`
- it can be split into tow display resolution and display type

`antutu`
- ex - AnTuTu Score 588,319 we can remove the text and comma

`price`
- rupees sign making it as string


**feature engineering**
- we can create a brand_name and brand_model from brand_name col

### programmatic assessing

- all the col are of string type
- no duplicated data

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand_name    4799 non-null   str
 1   processor     3492 non-null   str
 2   storage       4039 non-null   str
 3   back_camera   4674 non-null   str
 4   fron_camera   3618 non-null   str
 5   battery       4782 non-null   str
 6   display       4798 non-null   str
 7   anTuTu_score  1737 non-null   str
 8   price         4734 non-null   str
dtypes: str(9)
memory usage: 337.6 KB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.sample(15)

,brand_name,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
2779,Honor 8C,Snapdragon 632,4 GB RAM | 32 GB Storage,13 MP + 2 MP Rear Camera,8 MP Front Camera,4000 mAh,6.26 inches (15.9 cm) | IPS LCD,NaN,"₹12,999"
2101,Itel A26,Unisoc SC9832E,2 GB RAM | 32 GB Storage,5 MP Rear Camera,2 MP Front Camera,3020 mAh,5.7 inches (14.48 cm) | IPS LCD,NaN,"₹5,470"
3898,Mafe Nemo,NaN,NaN,0.3 MP Rear Camera,NaN,1050 mAh,1.8 inches (4.57 cm) | TFT,NaN,₹999
4116,Asus Zenfone 2 ZE551ML 4GB RAM 32GB 2.3GHz,Intel Atom,4 GB RAM | 32 GB Storage,13 MP Rear Camera,5 MP Front Camera,3000 mAh Fast Charging,5.5 inches (13.97 cm) | IPS LCD,NaN,"₹18,999"
3597,I Kall K44 New,NaN,NaN,0.3 MP Rear Camera,NaN,800 mAh,1.8 inches (4.57 cm) | TFT,NaN,₹999
3611,Lava A1 Buzz,NaN,NaN,0.3 MP Rear Camera,NaN,800 mAh,1.8 inches (4.57 cm) | TFT,NaN,"₹1,199"
2046,OnePlus 7T Pro McLaren Edition,Snapdragon 855 Plus,12 GB RAM | 256 GB Storage,48 MP + 16 MP + 8 MP Rear Camera,16 MP Front Camera,4085 mAh | 30W Warp Charging,6.67 inches (16.94 cm) | Fluid AMOLED,"AnTuTu Score 483,785","₹50,900"
4121,Lava Iris Fuel 25,MediaTek MT6572,512 MB RAM | 4 GB Storage,5 MP Rear Camera,0.3 MP Front Camera,3000 mAh,5.0 inches (12.7 cm) | TFT,NaN,"₹5,699"
505,iQOO Z10 Lite 256GB,MediaTek Dimensity 6300,8 GB RAM | 256 GB Storage,50 MP + 2 MP Rear Camera,5 MP Front Camera,6000 mAh | 15W Fast Charging,6.74 inches (17.12 cm) | LCD,NaN,"₹23,999"
3580,Asus ROG Phone 2 512GB,Snapdragon 855 Plus,12 GB RAM | 512 GB Storage,48 MP + 13 MP Rear Camera,24 MP Front Camera,6000 mAh Hyper Charging,6.59 inches (16.74 cm) | AMOLED,"AnTuTu Score 353,469","₹62,999"
4798,MTR Fold Z,NaN,32 MB RAM | 32 MB Storage,0.3 MP Rear Camera,NaN,2000 mAh,2.4 inches (6.1 cm) | TFT,NaN,"₹1,750"
3737,Samsung Galaxy On6,Samsung Exynos 7 Quad 7870,4 GB RAM | 64 GB Storage,13 MP Rear Camera,8 MP Front Camera,3000 mAh,5.6 inches (14.22 cm) | Super AMOLED,NaN,"₹17,600"
759,OnePlus Nord 5 12GB RAM,Snapdragon 8s Gen 3,12 GB RAM | 256 GB Storage,50 MP + 8 MP Rear Camera,50 MP Front Camera,6800 mAh | 80W Super VOOC Charging,6.83 inches (17.35 cm) | Swift AMOLED,"AnTuTu Score 1,481,616","₹48,999"
3702,Apple iPhone XS 256GB,Apple A12 Bionic,4 GB RAM | 256 GB Storage,12 MP + 12 MP Rear Camera,7 MP Front Camera,2658 mAh Fast Charging,5.8 inches (14.73 cm) | OLED,"AnTuTu Score 433,713","₹103,900"
3966,Asus Zenfone 3 Max,MediaTek MT6737,3 GB RAM | 32 GB Storage,13 MP Rear Camera,5 MP Front Camera,4100 mAh,5.2 inches (13.21 cm) | IPS LCD,NaN,"₹13,999"

In [7]:
Price = df['price'].str.replace('₹', '').str.replace(',', '')
df.insert(1, 'Price', value=Price)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand_name    4799 non-null   str
 1   Price         4734 non-null   str
 2   processor     3492 non-null   str
 3   storage       4039 non-null   str
 4   back_camera   4674 non-null   str
 5   fron_camera   3618 non-null   str
 6   battery       4782 non-null   str
 7   display       4798 non-null   str
 8   anTuTu_score  1737 non-null   str
 9   price         4734 non-null   str
dtypes: str(10)
memory usage: 375.1 KB

In [9]:
df['Price'] = df['Price'].fillna(0).astype(int)

In [10]:
df.sample(1)

,brand_name,Price,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
1657,iQOO 9 SE,30999,Snapdragon 888,8 GB RAM | 128 GB Storage,48 MP + 13 MP + 2 MP Rear Camera,16 MP Front Camera,4500 mAh | 66W Flash Charging,6.62 inches (16.81 cm) | AMOLED,AnTuTu Score 0,"₹30,999"

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand_name    4799 non-null   str
 1   Price         4800 non-null   int64
 2   processor     3492 non-null   str
 3   storage       4039 non-null   str
 4   back_camera   4674 non-null   str
 5   fron_camera   3618 non-null   str
 6   battery       4782 non-null   str
 7   display       4798 non-null   str
 8   anTuTu_score  1737 non-null   str
 9   price         4734 non-null   str
dtypes: int64(1), str(9)
memory usage: 375.1 KB

In [12]:
df1 = df

In [13]:
df[df['fron_camera'].isnull()]['Price'].describe()

count     1182.000000
mean      2004.302876
std       2927.946826
min          0.000000
25%        944.250000
50%       1229.500000
75%       1850.000000
max      39999.000000
Name: Price, dtype: float64

In [14]:
df[(df['Price'] == 35795)&(df['fron_camera'].isnull())]

,brand_name,Price,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
2995,Sony Ericsson Xperia X10,35795,Snapdragon S1,384 MB RAM | 1 GB Storage,8.1 MP Rear Camera,NaN,1500 mAh,4 inches (10.16 cm) | LCD,NaN,"₹35,795"

In [15]:
df.drop(1174, inplace=True)

In [16]:
df[(df['Price'] == 39999)&(df['fron_camera'].isnull())]

Empty DataFrame
Columns: [brand_name, Price, processor, storage, back_camera, fron_camera, battery, display, anTuTu_score, price]
Index: []

In [17]:
df[df['fron_camera'].isnull()]['Price'].describe()

count     1181.000000
mean      1972.131245
std       2712.142064
min          0.000000
25%        944.000000
50%       1229.000000
75%       1850.000000
max      35795.000000
Name: Price, dtype: float64

In [18]:
df.loc[df['brand_name'] == 'Motorola Razr 50 Ultra', 'display'] = df.loc[df['brand_name'] == 'Motorola Razr 50 Ultra','display'
].str.split(':').str[1]

In [19]:
df[df['brand_name'] == 'Motorola Razr 50 Ultra']

,brand_name,Price,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
737,Motorola Razr 50 Ultra,64811,Snapdragon 8s Gen 3,12 GB RAM | 512 GB Storage,50 MP + 50 MP Rear Camera,32 MP Front Camera,4000 mAh | 45W Turbo Power Charging,"6.9 inches pOLED, 3000 nits, 165 Hz refresh r...","AnTuTu Score 1,408,183","₹64,811"

In [20]:
display_size = df['display'].str.split('|').str[0].str.split(' ').str[0].fillna(0)
df.insert(8, 'display_size', value=display_size)

In [21]:
df['display_size'] = df['display_size'].replace('','0')

In [22]:
df[df['display_size']=='']

Empty DataFrame
Columns: [brand_name, Price, processor, storage, back_camera, fron_camera, battery, display, display_size, anTuTu_score, price]
Index: []

In [23]:
df['display_size'] = df['display_size'].astype(float)

In [24]:
df = df[df['display_size']>3]

In [25]:
df = df[df['storage'].str.contains('RAM')]

In [26]:
df.loc[df['brand_name'] == 'Motorola Razr 70 Plus', 'storage'] = '12 GB RAM | 256 GB Storage'
df.loc[df['brand_name'] == 'Motorola Razr 70 Plus', 'Price'] = 104990

### feature engineering

- we are going to create col such as brand and brand model
- ram and storage from storage col
- primary_rear_camera and no of rear camera from back_camera
- primary_front_camera from fron_camera
- battery_capacity and charging_type from battery col
- display_size and display_type form display col
- exact anTuTu score

In [27]:
df.sample(1)

,brand_name,Price,processor,storage,back_camera,fron_camera,battery,display,display_size,anTuTu_score,price
2675,vivo Y3s,9482,MediaTek Helio P35,2 GB RAM | 32 GB Storage,13 MP Rear Camera,5 MP Front Camera,5000 mAh | 10W,6.51 inches (16.54 cm) | IPS LCD,6.51,NaN,"₹9,482"

In [28]:
def len_of_list(l):
    return len(l)

In [29]:
brand = df['brand_name'].str.split(' ').str[0]
df.insert(0, 'brand', value=brand)

In [30]:
ram = df['storage'].str.split('|').str[0].str.split(' ').str[0]
df.insert(4, 'ram', value=ram)

In [31]:
storage_capacity = df['storage'].str.split('|').str[1].str.split(' ').str[1]
df.insert(5, 'storage_capacity', value=storage_capacity)

In [32]:
primary_rear_camera = df['back_camera'].str.split('+').str[0].str.split(' ').str[0]
df.insert(7, 'primary_rear_camera', value=primary_rear_camera)

In [33]:
front_camera = df['fron_camera'].str.split(' ').str[0]
df.insert(10, 'front_camera', value=front_camera)

In [34]:
battery_capacity  = df['battery'].str.split('|').str[0].str.split(' ').str[0]
df.insert(12, 'battery_capacity', value=battery_capacity)

In [35]:
charging_type = df['battery'].str.split('|').str[1]
df.insert(13, 'charging_type', value=charging_type)

In [36]:
display_type = df['display'].str.split('|').str[1]
df.insert(15, 'display_type', value=display_type)

In [37]:
antutu_score = df['anTuTu_score'].str.split(' ').str[2]
df.insert(17, 'antutu_score', value=antutu_score)

In [38]:
df.sample(1)

,brand,brand_name,Price,processor,ram,storage_capacity,storage,primary_rear_camera,back_camera,fron_camera,front_camera,battery,battery_capacity,charging_type,display,display_type,display_size,antutu_score,anTuTu_score,price
1645,Samsung,Samsung Galaxy M17 8GB RAM,15111,Samsung Exynos 1330,8,128,8 GB RAM | 128 GB Storage,50,50 MP + 5 MP + 2 MP Rear Camera,13 MP Front Camera,13,5000 mAh | 25W Fast Charging,5000,25W Fast Charging,6.7 inches (17.02 cm) | Super AMOLED,Super AMOLED,6.7,"608,564","AnTuTu Score 608,564","₹15,111"

In [39]:
camera_count = df['back_camera'].str.split('+').apply(len_of_list)
df.insert(8, 'camera_count', value=camera_count)

In [40]:
list_old_col = ['fron_camera', 'battery', 'price', 'anTuTu_score', 'display']

In [41]:
df = df.drop(columns=list_old_col)

In [42]:
df.sample(5)

,brand,brand_name,Price,processor,ram,storage_capacity,storage,primary_rear_camera,camera_count,back_camera,front_camera,battery_capacity,charging_type,display_type,display_size,antutu_score
3081,iQOO,iQOO Z7s 5G,19490,Snapdragon 695,6,128,6 GB RAM | 128 GB Storage,64,2,64 MP + 2 MP Rear Camera,16,4500,44W Flash Charging,AMOLED,6.38,NaN
670,Apple,Apple iPhone 17 512GB,102900,Apple A19,8,512,8 GB RAM | 512 GB Storage,48,2,48 MP + 48 MP Rear Camera,18,3692,40W Fast Charging,Super Retina XDR OLED,6.30,"2,250,422"
2662,Itel,Itel A27,5080,Unisoc SC9832E,2,32,2 GB RAM | 32 GB Storage,5,1,5 MP Rear Camera,2,4000,NaN,IPS LCD,5.45,NaN
2175,vivo,vivo Y28 5G 6GB RAM,12850,MediaTek Dimensity 6020,6,128,6 GB RAM | 128 GB Storage,50,2,50 MP + 2 MP Rear Camera,8,5000,15W,IPS LCD,6.56,NaN
163,Xiaomi,Xiaomi Redmi 12 6GB RAM,9999,MediaTek Helio G88,6,128,6 GB RAM | 128 GB Storage,50,3,50 MP + 8 MP + 2 MP Rear Camera,8,5000,18W Fast Charging,IPS LCD,6.79,NaN

In [43]:
df.info()

<class 'pandas.DataFrame'>
Index: 3611 entries, 0 to 4782
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                3610 non-null   object
 1   brand_name           3610 non-null   str
 2   Price                3611 non-null   int64
 3   processor            3448 non-null   str
 4   ram                  3611 non-null   object
 5   storage_capacity     3600 non-null   object
 6   storage              3611 non-null   str
 7   primary_rear_camera  3611 non-null   object
 8   camera_count         3611 non-null   int64
 9   back_camera          3611 non-null   str
 10  front_camera         3574 non-null   object
 11  battery_capacity     3611 non-null   object
 12  charging_type        2452 non-null   object
 13  display_type         3598 non-null   object
 14  display_size         3611 non-null   float64
 15  antutu_score         1735 non-null   object
dtypes: float64(1), int64(2), object(9), str(4)
memory usage: 479.6+ KB

In [44]:
df.rename(columns={'brand_name':'model'}, inplace=True)

In [45]:
df['ram'] = df['ram'].str.replace('GB','')
df['ram'] = df['ram'].astype(float)

In [46]:
df['primary_rear_camera'] = df['primary_rear_camera'].str.replace("MP","")
df['primary_rear_camera'] = df['primary_rear_camera'].astype(float)

df['front_camera'] = df['front_camera'].str.replace("MP","")
df['front_camera'] = df['front_camera'].astype(float)

In [47]:
df['battery_capacity'] = df['battery_capacity'].str.replace("mAh","")
df['battery_capacity'] = df['battery_capacity'].astype(int)

In [48]:
df['antutu_score'] = df['antutu_score'].str.replace(',', '', regex=True)
df['antutu_score'] = df['antutu_score'].astype('Int64')

In [49]:
df['storage_capacity'] = df['storage_capacity'].astype(float)

In [50]:
df.info()

<class 'pandas.DataFrame'>
Index: 3611 entries, 0 to 4782
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                3610 non-null   object
 1   model                3610 non-null   str
 2   Price                3611 non-null   int64
 3   processor            3448 non-null   str
 4   ram                  3611 non-null   float64
 5   storage_capacity     3600 non-null   float64
 6   storage              3611 non-null   str
 7   primary_rear_camera  3611 non-null   float64
 8   camera_count         3611 non-null   int64
 9   back_camera          3611 non-null   str
 10  front_camera         3574 non-null   float64
 11  battery_capacity     3611 non-null   int64
 12  charging_type        2452 non-null   object
 13  display_type         3598 non-null   object
 14  display_size         3611 non-null   float64
 15  antutu_score         1735 non-null   Int64
dtypes: Int64(1), float64(5), int64(3), object(3), str(4)
memory usage: 483.1+ KB

In [51]:
# df.drop(index=[3034, 4278, 4290, 4306, 4494], inplace=True)
df.drop(index=[2515], inplace=True)

In [52]:
temp_df = df[(df['ram']>18) & (df['storage_capacity']>16)][['ram', 'storage_capacity']]/1024

In [53]:
df.loc[temp_df.index, ['ram', 'storage_capacity']] = temp_df.values

In [54]:
processor_brand = df['processor'].str.split(' ').str[0]
df.insert(3, 'processor_brand', processor_brand)

In [55]:
df['charging_type'] = df['charging_type'].str.strip().str.split(' ').str[0].str.split('W').str[0].astype(float)

In [56]:
def set_tier(price):
    if price<15000:
        return "Budget Tier"
    elif price < 30000:
        return "Mid Tier"
    elif price < 45000:
        return "High Tier"
    else:
        return "Ultra-Premium Tier"

In [57]:
price_tier = df['Price'].apply(set_tier)
df.insert(3, "price_tier", price_tier)

In [58]:
temp_df = df[df['Price']==0]
df.drop(index=temp_df.index, inplace=True)

In [59]:
df[df['brand'].isnull()]

,brand,model,Price,price_tier,processor_brand,processor,ram,storage_capacity,storage,primary_rear_camera,camera_count,back_camera,front_camera,battery_capacity,charging_type,display_type,display_size,antutu_score
1175,NaN,NaN,121999,Ultra-Premium Tier,Samsung,Samsung Exynos 2500,12.0,512.0,12 GB RAM | 512 GB Storage,50.0,2,50 MP + 12 MP Rear Camera,10.0,4300,25.0,Dynamic AMOLED 2x (Main Display),6.9,<NA>

In [60]:
df.loc[1175, ['brand', 'model']] = ['Samsung', 'Samsung Galaxy Z Flip7']

In [61]:
df[df['brand'].isnull()]

Empty DataFrame
Columns: [brand, model, Price, price_tier, processor_brand, processor, ram, storage_capacity, storage, primary_rear_camera, camera_count, back_camera, front_camera, battery_capacity, charging_type, display_type, display_size, antutu_score]
Index: []

In [66]:
df['display_type'].value_counts()

display_type
IPS LCD                             1592
AMOLED                               631
LCD                                  248
Super AMOLED                         229
TFT                                  143
OLED                                  76
Super Retina XDR                      76
Dynamic AMOLED 2x                     59
PLS LCD                               52
P-OLED                                44
Flexible AMOLED                       43
Fluid AMOLED                          42
PLS TFT LCD                           39
LTPO AMOLED                           38
Super AMOLED Plus                     28
Dynamic AMOLED 2x (Main Display)      25
LTPS AMOLED                           18
Super Retina XDR OLED                 14
LTPO OLED                             13
AMOLED (Main Display)                 13
ProXDR LTPO                           11
Extreme AMOLED                         9
LTPS LCD                               8
Super Fluid AMOLED                     7
Optic AMOLED                           6
Dynamic AMOLED (Main Display)          5
IPS LCD (Main Display)                 5
LTPS OLED                              4
LTPO AMOLED (Main Display)             4
P-OLED (Main Display)                  4
TFT LCD                                4
S-LCD                                  4
Swift AMOLED                           3
Flow AMOLED                            3
Hyper Glow AMOLED                      3
Dynamic AMOLED                         3
IPS LED                                3
Sunburst AMOLED                        2
TFT IPS                                2
OLED (Main Display)                    2
Flat OLED                              2
LTPS IPS                               2
LTPO Flexi-fluid AMOLED                2
S-LCD 5                                2
S-LCD 3                                2
S-LCD 2                                2
LTPO OLED (Main Display)               1
S-LCD 6                                1
Super PLS LCD                          1
S-LCD 5 (Main Display)                 1
True HD IPS Plus LCD                   1
TFD                                    1
Name: count, dtype: int64

In [93]:
lcd_list = ['IPS LCD', 'LCD', 'LTPS LCD', 'IPS LED', 'TFT IPS', 'LTPS IPS', 'PLS LCD', 'PLS TFT LCD', 'Super PLS LCD', 'S-LCD', 'True HD IPS Plus LCD', 'IPS LCD (Main Display)', 'S-LCD 5', 'S-LCD 3', 'S-LCD 2', 'S-LCD 6', 'S-LCD 5 (Main Display)']

tft_list = ['TFT', 'TFT LCD', 'TFD']

poled_list = ['P-OLED', 'P-OLED (Main Display)', 'LTPO P-OLED']

amoled_list = ['AMOLED', 'Super AMOLED', 'Dynamic AMOLED 2x', 'Fluid AMOLED', 'LTPO AMOLED', 'Flexible AMOLED', 'Super AMOLED Plus', 'LTPS AMOLED', 'Optic AMOLED', 'Extreme AMOLED', 'Dynamic AMOLED 2x (Main Display)', 'AMOLED (Main Display)', 'Super Fluid AMOLED', 'Dynamic AMOLED (Main Display)', 'LTPO AMOLED (Main Display)', 'Swift AMOLED', 'Flow AMOLED', 'Hyper Glow AMOLED', 'Dynamic AMOLED', 'Sunburst AMOLED', 'LTPO Flexi-fluid AMOLED', ]

oled_list = ['OLED', 'Super Retina XDR', 'Super Retina XDR OLED', 'LTPO OLED', 'Flat OLED', 'LTPS OLED', 'ProXDR LTPO', 'OLED (Main Display)','LTPO OLED (Main Display)']

In [94]:
df['display_type'] = df['display_type'].str.strip().replace(lcd_list, 'LCD')
df['display_type'] = df['display_type'].str.strip().replace(tft_list, 'TFT')
df['display_type'] = df['display_type'].str.strip().replace(poled_list, 'POLED')
df['display_type'] = df['display_type'].str.strip().replace(amoled_list, 'AMOLED')
df['display_type'] = df['display_type'].str.strip().replace(oled_list, 'OLED')

In [85]:
# df['display_type'].isin(amoled_list).sum()

np.int64(1094)

In [95]:
df.head(5)

,brand,model,Price,price_tier,processor_brand,processor,ram,storage_capacity,storage,primary_rear_camera,camera_count,back_camera,front_camera,battery_capacity,charging_type,display_type,display_size,antutu_score
0,vivo,vivo S2 5G,39490,High Tier,MediaTek,MediaTek Dimensity 7360 Turbo,8.0,128.0,8 GB RAM | 128 GB Storage,50.0,2,50 MP + 2 MP Rear Camera,32.0,7050,44.0,AMOLED,6.83,956029
1,Motorola,Motorola Edge 70 Fusion,28990,Mid Tier,Snapdragon,Snapdragon 7s Gen 4,8.0,128.0,8 GB RAM | 128 GB Storage,50.0,2,50 MP + 13 MP Rear Camera,32.0,7000,68.0,AMOLED,6.80,1149292
3,iQOO,iQOO Z11 5G,34999,High Tier,MediaTek,MediaTek Dimensity 7500 turbo,6.0,128.0,6 GB RAM | 128 GB Storage,50.0,2,50 MP + 8 MP Rear Camera,32.0,7050,44.0,AMOLED,6.83,1099769
4,Xiaomi,Xiaomi Redmi Note 17 5G,27999,Mid Tier,Snapdragon,Snapdragon 4 Gen 4,6.0,128.0,6 GB RAM | 128 GB Storage,50.0,2,50 MP + 2 MP Rear Camera,8.0,8000,45.0,OLED,6.99,626958
7,vivo,vivo T4X,16999,Mid Tier,MediaTek,MediaTek Dimensity 7300,6.0,128.0,6 GB RAM | 128 GB Storage,50.0,2,50 MP + 2 MP Rear Camera,8.0,6500,44.0,LCD,6.72,685052

In [96]:
df['display_type'].value_counts()

display_type
LCD       1965
AMOLED    1173
OLED       199
TFT        148
POLED       48
Name: count, dtype: int64

In [97]:
df.info()

<class 'pandas.DataFrame'>
Index: 3545 entries, 0 to 4782
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                3545 non-null   object
 1   model                3545 non-null   str
 2   Price                3545 non-null   int64
 3   price_tier           3545 non-null   str
 4   processor_brand      3383 non-null   object
 5   processor            3383 non-null   str
 6   ram                  3545 non-null   float64
 7   storage_capacity     3535 non-null   float64
 8   storage              3545 non-null   str
 9   primary_rear_camera  3545 non-null   float64
 10  camera_count         3545 non-null   int64
 11  back_camera          3545 non-null   str
 12  front_camera         3511 non-null   float64
 13  battery_capacity     3545 non-null   int64
 14  charging_type        2393 non-null   float64
 15  display_type         3533 non-null   object
 16  display_size         3545 non-null   float64
 17  antutu_score         1734 non-null   Int64
dtypes: Int64(1), float64(6), int64(3), object(3), str(5)
memory usage: 658.7+ KB

In [98]:
col_to_drop = ['storage', 'back_camera']
df.drop(columns=col_to_drop, inplace=True)

In [99]:
df.info()

<class 'pandas.DataFrame'>
Index: 3545 entries, 0 to 4782
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                3545 non-null   object
 1   model                3545 non-null   str
 2   Price                3545 non-null   int64
 3   price_tier           3545 non-null   str
 4   processor_brand      3383 non-null   object
 5   processor            3383 non-null   str
 6   ram                  3545 non-null   float64
 7   storage_capacity     3535 non-null   float64
 8   primary_rear_camera  3545 non-null   float64
 9   camera_count         3545 non-null   int64
 10  front_camera         3511 non-null   float64
 11  battery_capacity     3545 non-null   int64
 12  charging_type        2393 non-null   float64
 13  display_type         3533 non-null   object
 14  display_size         3545 non-null   float64
 15  antutu_score         1734 non-null   Int64
dtypes: Int64(1), float64(6), int64(3), object(3), str(3)
memory usage: 603.3+ KB

In [101]:
df.head(8)

,brand,model,Price,price_tier,processor_brand,processor,ram,storage_capacity,primary_rear_camera,camera_count,front_camera,battery_capacity,charging_type,display_type,display_size,antutu_score
0,vivo,vivo S2 5G,39490,High Tier,MediaTek,MediaTek Dimensity 7360 Turbo,8.0,128.0,50.0,2,32.0,7050,44.0,AMOLED,6.83,956029
1,Motorola,Motorola Edge 70 Fusion,28990,Mid Tier,Snapdragon,Snapdragon 7s Gen 4,8.0,128.0,50.0,2,32.0,7000,68.0,AMOLED,6.80,1149292
3,iQOO,iQOO Z11 5G,34999,High Tier,MediaTek,MediaTek Dimensity 7500 turbo,6.0,128.0,50.0,2,32.0,7050,44.0,AMOLED,6.83,1099769
4,Xiaomi,Xiaomi Redmi Note 17 5G,27999,Mid Tier,Snapdragon,Snapdragon 4 Gen 4,6.0,128.0,50.0,2,8.0,8000,45.0,OLED,6.99,626958
7,vivo,vivo T4X,16999,Mid Tier,MediaTek,MediaTek Dimensity 7300,6.0,128.0,50.0,2,8.0,6500,44.0,LCD,6.72,685052
8,vivo,vivo T5x,27299,Mid Tier,MediaTek,MediaTek Dimensity 7400 Turbo,6.0,128.0,50.0,2,32.0,7200,44.0,LCD,6.76,<NA>
9,Motorola,Motorola Edge 60 Fusion,20900,Mid Tier,MediaTek,MediaTek Dimensity 7400,8.0,128.0,50.0,2,32.0,5500,68.0,POLED,6.67,692185
11,Samsung,Samsung Galaxy F70 Pro 5G,26337,Mid Tier,Snapdragon,Snapdragon 6 Gen 3,6.0,128.0,50.0,3,12.0,6000,45.0,AMOLED,6.70,<NA>

In [100]:
df.to_csv("cleaned_df.csv", index=False)