In [183]:
import numpy as np
import pandas as pd

In [184]:
df = pd.read_csv(r"C:\Users\harsh\Documents\data Analyst Projects\complex_phone_data\data_scraping\final_ds.csv")

In [185]:
df.sample(2)

,brand_name,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
2084,Xiaomi Redmi Note 12 4G 128GB,Snapdragon 685,6 GB RAM | 128 GB Storage,50 MP + 8 MP + 2 MP Rear Camera,13 MP Front Camera,5000 mAh | 33W Fast Charging,6.67 inches (16.94 cm) | Super AMOLED,NaN,"₹12,499"
406,Samsung Galaxy F16 5G 8GB RAM,MediaTek Dimensity 6300,8 GB RAM | 128 GB Storage,50 MP + 5 MP + 2 MP Rear Camera,13 MP Front Camera,5000 mAh | 25W Fast Charging,6.7 inches (17.02 cm) | Super AMOLED,NaN,"₹15,499"

## Data Assessing

#### mannual assessing

`brand name`
- data in row 1177 is missing

`processor`
- row no 1494 has nm info in processor

`storage`
- ram and rom both are present in same col /
- row no 62 have type of storage info
- row 2307, 2849, 2952, 2958, 2981, 2982, 2983, 2985, 2986, 2987, 2989, 2993, 2994, 2995, 2996, 2998, 2999, 3000, 4128 , 4211, 4306, 4310,315, 4316, 4322, 4331, 4332, 4334, 4336, 4340, 4342, 4352, 4357, 4358, 4359, 4377, 4379, 4383, 4387, 4389, 4393, 4396, 4398, 4400, 4402, 4403, 4404, 4406, 4407, 4408, 4409, 4412, 4413, 4414, 4415, 4417, 4422, 4423, 4424, 4425, 4426, 4427, 4431, 4450, 4452, 4466, 4467, 4468 have only storage

- row 4025, 4086, 4183, 4204, 4233, 4297, 4305, 4314,
  4420, 4447, 4448, 4456, 4558 have only ram

`battery`
- this col can be split into two 1st battery and 2nd charging speed
- at some places it's directly mentioned 3000 mAh Fast Charging, 3300 mAh Quick Charging, 5000 mAh | 10W Fast Charging

`display`
- it can be split into tow display resolution and display type

`antutu`
- ex - AnTuTu Score 588,319 we can remove the text and comma

`price`
- rupees sign making it as string


**feature engineering**
- we can create a brand_name and brand_model from brand_name col

### programmatic assessing

- all the col are of string type
- no duplicated data

In [186]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand_name    4799 non-null   str
 1   processor     3492 non-null   str
 2   storage       4039 non-null   str
 3   back_camera   4674 non-null   str
 4   fron_camera   3618 non-null   str
 5   battery       4782 non-null   str
 6   display       4798 non-null   str
 7   anTuTu_score  1737 non-null   str
 8   price         4734 non-null   str
dtypes: str(9)
memory usage: 337.6 KB

In [187]:
df.duplicated().sum()

np.int64(0)

In [188]:
df.sample(15)

,brand_name,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
1822,Motorola Razr 40 Ultra,Snapdragon 8 Plus Gen 1,8 GB RAM | 256 GB Storage,12 MP + 13 MP Rear Camera,32 MP Front Camera,3800 mAh | 30W Turbo Power Charging,6.9 inches (17.53 cm) | P-OLED (Main Display),"AnTuTu Score 1,063,156","₹49,000"
2101,Itel A26,Unisoc SC9832E,2 GB RAM | 32 GB Storage,5 MP Rear Camera,2 MP Front Camera,3020 mAh,5.7 inches (14.48 cm) | IPS LCD,NaN,"₹5,470"
1971,Sony Xperia Z5 Premium Dual,Snapdragon 810,3 GB RAM | 32 GB Storage,23 MP Rear Camera,5 MP Front Camera,3430 mAh Quick Charging,5.5 inches (13.97 cm) | IPS LCD,NaN,"₹62,990"
973,OPPO Reno12 Pro 512GB,MediaTek Dimensity 7300 Energy,12 GB RAM | 512 GB Storage,50 MP + 8 MP + 50 MP Rear Camera,50 MP Front Camera,5000 mAh | 80W Super VOOC Charging,6.7 inches (17.02 cm) | Flexible AMOLED,"AnTuTu Score 638,962","₹52,499"
1735,iQOO Z6 Pro,Snapdragon 778G,6 GB RAM | 128 GB Storage,64 MP + 8 MP + 2 MP Rear Camera,16 MP Front Camera,4700 mAh | 66W Flash Charging,6.44 inches (16.36 cm) | AMOLED,"AnTuTu Score 550,719","₹22,999"
1386,Xiaomi Redmi A4,Snapdragon 8 Gen 3,12 GB RAM | 256 GB Storage,50 MP + 48 MP + 64 MP Rear Camera,32 MP Front Camera,5400 mAh | 100W Super VOOC Charging,6.82 inches (17.32 cm) | ProXDR LTPO,"AnTuTu Score 1,738,936","₹50,399"
1462,Samsung Galaxy M51,Snapdragon 730G,6 GB RAM | 128 GB Storage,64 MP + 12 MP + 5 MP + 5 MP Rear Camera,32 MP Front Camera,7000 mAh | 25W Fast Charging,6.7 inches (17.02 cm) | Super AMOLED Plus,"AnTuTu Score 224,310","₹22,990"
3295,Xiaomi Redmi Note 10 Lite 128GB,Snapdragon 720G,4 GB RAM | 128 GB Storage,48 MP + 8 MP + 5 MP + 2 MP Rear Camera,16 MP Front Camera,5020 mAh | 18W Fast Charging,6.67 inches (16.94 cm) | IPS LCD,"AnTuTu Score 307,976","₹10,999"
860,realme C33 2023,Unisoc T612,4 GB RAM | 64 GB Storage,50 MP + 0.3 MP Rear Camera,5 MP Front Camera,5000 mAh | 10W,6.5 inches (16.51 cm) | IPS LCD,NaN,"₹9,999"
4219,Lava ARC 22,NaN,NaN,1.3 MP Rear Camera,NaN,1150 mAh,2.8 inches (7.11 cm) | TFT,NaN,"₹1,799"
311,Xiaomi Redmi 12 5G 8GB RAM,Snapdragon 4 Gen 2,8 GB RAM | 256 GB Storage,50 MP + 2 MP Rear Camera,8 MP Front Camera,5000 mAh | 18W Fast Charging,6.79 inches (17.25 cm) | IPS LCD,"AnTuTu Score 431,098","₹14,499"
1551,Xiaomi Redmi 12,MediaTek Helio G88,4 GB RAM | 128 GB Storage,50 MP + 8 MP + 2 MP Rear Camera,8 MP Front Camera,5000 mAh | 18W Fast Charging,6.79 inches (17.25 cm) | IPS LCD,NaN,"₹9,499"
4450,Alcatel Idol OT-6030a,NaN,4 GB Storage,8 MP Rear Camera,2 MP Front Camera,1800 mAh,4.7 inches (11.94 cm) | IPS LCD,NaN,"₹13,999"
1138,realme GT Neo 3T 5G 8GB RAM,Snapdragon 870,8 GB RAM | 128 GB Storage,64 MP + 8 MP + 2 MP Rear Camera,16 MP Front Camera,5000 mAh | 80W Super Dart Charging,6.62 inches (16.81 cm) | AMOLED,"AnTuTu Score 715,648","₹31,999"
3154,Nokia G11 Plus,Unisoc T606,4 GB RAM | 64 GB Storage,50 MP + 2 MP Rear Camera,8 MP Front Camera,5000 mAh | 10W,6.51 inches (16.54 cm) | IPS LCD,NaN,"₹13,999"

In [189]:
Price = df['price'].str.replace('₹', '').str.replace(',', '')
df.insert(1, 'Price', value=Price)

In [190]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand_name    4799 non-null   str
 1   Price         4734 non-null   str
 2   processor     3492 non-null   str
 3   storage       4039 non-null   str
 4   back_camera   4674 non-null   str
 5   fron_camera   3618 non-null   str
 6   battery       4782 non-null   str
 7   display       4798 non-null   str
 8   anTuTu_score  1737 non-null   str
 9   price         4734 non-null   str
dtypes: str(10)
memory usage: 375.1 KB

In [191]:
df['Price'] = df['Price'].fillna(0).astype(int)

In [192]:
df.sample(1)

,brand_name,Price,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
2879,Xiaomi Redmi 3S,6999,Snapdragon 430,2 GB RAM | 16 GB Storage,13 MP Rear Camera,5 MP Front Camera,4100 mAh Fast Charging,5.0 inches (12.7 cm) | IPS LCD,NaN,"₹6,999"

In [193]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand_name    4799 non-null   str
 1   Price         4800 non-null   int64
 2   processor     3492 non-null   str
 3   storage       4039 non-null   str
 4   back_camera   4674 non-null   str
 5   fron_camera   3618 non-null   str
 6   battery       4782 non-null   str
 7   display       4798 non-null   str
 8   anTuTu_score  1737 non-null   str
 9   price         4734 non-null   str
dtypes: int64(1), str(9)
memory usage: 375.1 KB

In [194]:
df1 = df

In [195]:
df[df['fron_camera'].isnull()]['Price'].describe()

count     1182.000000
mean      2004.302876
std       2927.946826
min          0.000000
25%        944.250000
50%       1229.500000
75%       1850.000000
max      39999.000000
Name: Price, dtype: float64

In [196]:
df[(df['Price'] == 35795)&(df['fron_camera'].isnull())]

,brand_name,Price,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
2995,Sony Ericsson Xperia X10,35795,Snapdragon S1,384 MB RAM | 1 GB Storage,8.1 MP Rear Camera,NaN,1500 mAh,4 inches (10.16 cm) | LCD,NaN,"₹35,795"

In [197]:
df.drop(1174, inplace=True)

In [198]:
df[(df['Price'] == 39999)&(df['fron_camera'].isnull())]

Empty DataFrame
Columns: [brand_name, Price, processor, storage, back_camera, fron_camera, battery, display, anTuTu_score, price]
Index: []

In [199]:
df[df['fron_camera'].isnull()]['Price'].describe()

count     1181.000000
mean      1972.131245
std       2712.142064
min          0.000000
25%        944.000000
50%       1229.000000
75%       1850.000000
max      35795.000000
Name: Price, dtype: float64

In [200]:
df.loc[df['brand_name'] == 'Motorola Razr 50 Ultra', 'display'] = df.loc[df['brand_name'] == 'Motorola Razr 50 Ultra','display'
].str.split(':').str[1]

In [201]:
df[df['brand_name'] == 'Motorola Razr 50 Ultra']

,brand_name,Price,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
737,Motorola Razr 50 Ultra,64811,Snapdragon 8s Gen 3,12 GB RAM | 512 GB Storage,50 MP + 50 MP Rear Camera,32 MP Front Camera,4000 mAh | 45W Turbo Power Charging,"6.9 inches pOLED, 3000 nits, 165 Hz refresh r...","AnTuTu Score 1,408,183","₹64,811"

In [202]:
display_size = df['display'].str.split('|').str[0].str.split(' ').str[0].fillna(0)
df.insert(8, 'display_size', value=display_size)

In [203]:
df['display_size'] = df['display_size'].replace('','0')

In [204]:
df[df['display_size']=='']

Empty DataFrame
Columns: [brand_name, Price, processor, storage, back_camera, fron_camera, battery, display, display_size, anTuTu_score, price]
Index: []

In [205]:
df['display_size'] = df['display_size'].astype(float)

In [206]:
df = df[df['display_size']>3]

In [207]:
df = df[df['storage'].str.contains('RAM')]

In [208]:
df.loc[df['brand_name'] == 'Motorola Razr 70 Plus', 'storage'] = '12 GB RAM | 256 GB Storage'
df.loc[df['brand_name'] == 'Motorola Razr 70 Plus', 'Price'] = 104990

### feature engineering

- we are going to create col such as brand and brand model
- ram and storage from storage col
- primary_rear_camera and no of rear camera from back_camera
- primary_front_camera from fron_camera
- battery_capacity and charging_type from battery col
- display_size and display_type form display col
- exact anTuTu score

In [209]:
df.sample(1)

,brand_name,Price,processor,storage,back_camera,fron_camera,battery,display,display_size,anTuTu_score,price
1155,Samsung Galaxy A12 128GB,12649,MediaTek Helio P35,4 GB RAM | 128 GB Storage,48 MP + 5 MP + 2 MP + 2 MP Rear Camera,8 MP Front Camera,5000 mAh | 15W Fast Charging,6.5 inches (16.51 cm) | PLS TFT LCD,6.5,"AnTuTu Score 109,789","₹12,649"

In [210]:
def len_of_list(l):
    return len(l)

In [211]:
brand = df['brand_name'].str.split(' ').str[0]
df.insert(0, 'brand', value=brand)

In [212]:
ram = df['storage'].str.split('|').str[0].str.split(' ').str[0]
df.insert(4, 'ram', value=ram)

In [213]:
storage_capacity = df['storage'].str.split('|').str[1].str.split(' ').str[1]
df.insert(5, 'storage_capacity', value=storage_capacity)

In [214]:
primary_rear_camera = df['back_camera'].str.split('+').str[0].str.split(' ').str[0]
df.insert(7, 'primary_rear_camera', value=primary_rear_camera)

In [215]:
front_camera = df['fron_camera'].str.split(' ').str[0]
df.insert(10, 'front_camera', value=front_camera)

In [216]:
battery_capacity  = df['battery'].str.split('|').str[0].str.split(' ').str[0]
df.insert(12, 'battery_capacity', value=battery_capacity)

In [217]:
charging_type = df['battery'].str.split('|').str[1]
df.insert(13, 'charging_type', value=charging_type)

In [218]:
display_type = df['display'].str.split('|').str[1]
df.insert(15, 'display_type', value=display_type)

In [219]:
antutu_score = df['anTuTu_score'].str.split(' ').str[2]
df.insert(17, 'antutu_score', value=antutu_score)

In [220]:
df.sample(1)

,brand,brand_name,Price,processor,ram,storage_capacity,storage,primary_rear_camera,back_camera,fron_camera,front_camera,battery,battery_capacity,charging_type,display,display_type,display_size,antutu_score,anTuTu_score,price
213,Moto,Moto G35,12499,Unisoc T760,4,128,4 GB RAM | 128 GB Storage,50,50 MP + 8 MP Rear Camera,16 MP Front Camera,16,5000 mAh | 18W Fast Charging,5000,18W Fast Charging,6.72 inches (17.07 cm) | LTPS LCD,LTPS LCD,6.72,NaN,NaN,"₹12,499"

In [221]:
camera_count = df['back_camera'].str.split('+').apply(len_of_list)
df.insert(8, 'camera_count', value=camera_count)

In [222]:
list_old_col = ['storage', 'fron_camera', 'battery', 'price', 'anTuTu_score', 'display']

In [223]:
df = df.drop(columns=list_old_col)

In [224]:
df.sample(5)

,brand,brand_name,Price,processor,ram,storage_capacity,primary_rear_camera,camera_count,back_camera,front_camera,battery_capacity,charging_type,display_type,display_size,antutu_score
776,Lava,Lava Bold N2 5G 128GB,14499,Unisoc T8200,4,128,13,1,13 MP Rear Camera,5,6000,NaN,LCD,6.75,"515,768"
250,iQOO,iQOO Z10 Lite,16999,MediaTek Dimensity 6300,4,64,50,2,50 MP + 2 MP Rear Camera,5,6000,15W Fast Charging,LCD,6.74,"425,577"
1691,realme,realme Narzo 60 Pro 5G,23310,MediaTek Dimensity 7050,8,128,100,2,100 MP + 2 MP Rear Camera,16,5000,67W Super VOOC Charging,AMOLED,6.70,0
849,Nokia,Nokia C30,9999,Unisoc SC9863A,3,32,13,2,13 MP + 2 MP Rear Camera,5,6000,10W,IPS LCD,6.82,0
70,Samsung,Samsung Galaxy S25 Ultra,139999,Snapdragon 8 Elite,12,256,200,4,200 MP + 50 MP + 10 MP + 50 MP Rear Camera,12,5000,45W Fast Charging,Dynamic AMOLED 2x,6.90,"2,209,231"

In [225]:
df.info()

<class 'pandas.DataFrame'>
Index: 3611 entries, 0 to 4782
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                3610 non-null   object
 1   brand_name           3610 non-null   str
 2   Price                3611 non-null   int64
 3   processor            3448 non-null   str
 4   ram                  3611 non-null   object
 5   storage_capacity     3600 non-null   object
 6   primary_rear_camera  3611 non-null   object
 7   camera_count         3611 non-null   int64
 8   back_camera          3611 non-null   str
 9   front_camera         3574 non-null   object
 10  battery_capacity     3611 non-null   object
 11  charging_type        2452 non-null   object
 12  display_type         3598 non-null   object
 13  display_size         3611 non-null   float64
 14  antutu_score         1735 non-null   object
dtypes: float64(1), int64(2), object(9), str(3)
memory usage: 451.4+ KB

In [226]:
df.rename(columns={'brand_name':'model'}, inplace=True)

In [227]:
df['ram'] = df['ram'].str.replace('GB','')
df['ram'] = df['ram'].astype(float)

In [228]:
df['primary_rear_camera'] = df['primary_rear_camera'].str.replace("MP","")
df['primary_rear_camera'] = df['primary_rear_camera'].astype(float)

df['front_camera'] = df['front_camera'].str.replace("MP","")
df['front_camera'] = df['front_camera'].astype(float)

In [229]:
df['battery_capacity'] = df['battery_capacity'].str.replace("mAh","")
df['battery_capacity'] = df['battery_capacity'].astype(int)

In [230]:
df['antutu_score'] = df['antutu_score'].str.replace(',', '', regex=True)
df['antutu_score'] = df['antutu_score'].astype('Int64')

In [231]:
df.to_csv("cleaned_df.csv", index=False)