In [445]:

import numpy as np
import pandas as pd

In [446]:
df = pd.read_csv(r"C:\Users\harsh\Documents\data Analyst Projects\complex_phone_data\data_scraping\final_ds.csv")

In [447]:
df.sample(2)

,brand_name,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
2299,Lava Iris 506Q,NaN,512 MB RAM | 4 GB Storage,5 MP Rear Camera,0.3 MP Front Camera,2000 mAh,5 inches (12.7 cm) | TFT,NaN,"₹9,999"
1450,realme 15 Lite,MediaTek Dimensity 7300 Energy,8 GB RAM | 128 GB Storage,50 MP + 2 MP Rear Camera,16 MP Front Camera,5000 mAh | 80W Fast Charging,6.67 inches (16.94 cm) | OLED,NaN,"₹15,045"

## Data Assessing

#### mannual assessing

`brand name`
- data in row 1177 is missing

`processor`
- row no 1494 has nm info in processor

`storage`
- ram and rom both are present in same col /
- row no 62 have type of storage info
- row 2307, 2849, 2952, 2958, 2981, 2982, 2983, 2985, 2986, 2987, 2989, 2993, 2994, 2995, 2996, 2998, 2999, 3000, 4128 , 4211, 4306, 4310,315, 4316, 4322, 4331, 4332, 4334, 4336, 4340, 4342, 4352, 4357, 4358, 4359, 4377, 4379, 4383, 4387, 4389, 4393, 4396, 4398, 4400, 4402, 4403, 4404, 4406, 4407, 4408, 4409, 4412, 4413, 4414, 4415, 4417, 4422, 4423, 4424, 4425, 4426, 4427, 4431, 4450, 4452, 4466, 4467, 4468 have only storage

- row 4025, 4086, 4183, 4204, 4233, 4297, 4305, 4314,
  4420, 4447, 4448, 4456, 4558 have only ram

`battery`
- this col can be split into two 1st battery and 2nd charging speed
- at some places it's directly mentioned 3000 mAh Fast Charging, 3300 mAh Quick Charging, 5000 mAh | 10W Fast Charging

`display`
- it can be split into tow display resolution and display type

`antutu`
- ex - AnTuTu Score 588,319 we can remove the text and comma

`price`
- rupees sign making it as string


**feature engineering**
- we can create a brand_name and brand_model from brand_name col

### programmatic assessing

- all the col are of string type
- no duplicated data

In [448]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand_name    4799 non-null   str
 1   processor     3492 non-null   str
 2   storage       4039 non-null   str
 3   back_camera   4674 non-null   str
 4   fron_camera   3618 non-null   str
 5   battery       4782 non-null   str
 6   display       4798 non-null   str
 7   anTuTu_score  1737 non-null   str
 8   price         4734 non-null   str
dtypes: str(9)
memory usage: 337.6 KB

In [449]:
df.duplicated().sum()

np.int64(0)

In [450]:
df.sample(15)

,brand_name,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
838,Samsung Galaxy M52 5G 8GB RAM,Snapdragon 778G,8 GB RAM | 128 GB Storage,64 MP + 12 MP + 5 MP Rear Camera,32 MP Front Camera,5000 mAh | 25W Fast Charging,6.7 inches (17.02 cm) | Super AMOLED Plus,AnTuTu Score 0,"₹25,749"
1533,realme Narzo 60 Pro 5G 1TB,MediaTek Dimensity 7050,12 GB RAM | 1 TB Storage,100 MP + 2 MP Rear Camera,16 MP Front Camera,5000 mAh | 67W Super VOOC Charging,6.7 inches (17.02 cm) | AMOLED,"AnTuTu Score 569,173","₹23,488"
3646,Karbonn K1 Prime,NaN,NaN,0.3 MP Rear Camera,NaN,800 mAh,1.8 inches (4.57 cm) | TFT,NaN,₹749
49,vivo V60e,MediaTek Dimensity 7360 Turbo,8 GB RAM | 128 GB Storage,200 MP + 8 MP Rear Camera,50 MP Front Camera,6500 mAh | 90W Flash Charging,6.77 inches (17.2 cm) | AMOLED,"AnTuTu Score 882,692","₹26,494"
2034,POCO M4 Pro 128GB,MediaTek Helio G96,6 GB RAM | 128 GB Storage,64 MP + 8 MP + 2 MP Rear Camera,16 MP Front Camera,5000 mAh | 33W Fast Charging,6.43 inches (16.33 cm) | AMOLED,"AnTuTu Score 309,983","₹9,999"
443,vivo Y400 256GB,Snapdragon 4 Gen 2,8 GB RAM | 256 GB Storage,50 MP + 2 MP Rear Camera,32 MP Front Camera,6000 mAh | 90W Flash Charging,6.67 inches (16.94 cm) | AMOLED,"AnTuTu Score 478,134","₹27,999"
1143,Micromax J22,NaN,32 MB RAM | 32 MB Storage,NaN,NaN,1000 mAh,2.4 inches (6.1 cm) | TFT,NaN,"₹1,363"
1258,Micromax X379,NaN,NaN,NaN,NaN,1000 mAh,1.8 inches (4.57 cm) | TFT,NaN,₹740
4504,iQOO 9 Pro 5G,Snapdragon 8 Gen 1,8 GB RAM | 256 GB Storage,50 MP + 50 MP + 16 MP Rear Camera,16 MP Front Camera,4700 mAh | 120W Flash Charging,6.78 inches (17.22 cm) | AMOLED,"AnTuTu Score 993,826","₹39,999"
3225,Itel Ace Star,NaN,4 MB RAM | 4 MB Storage,NaN,NaN,1000 mAh,1.8 inches (4.57 cm) | TFT,NaN,₹999
3332,Infinix Smart 5A,MediaTek Helio A20,2 GB RAM | 32 GB Storage,8 MP Rear Camera,8 MP Front Camera,5000 mAh | 10W,6.52 inches (16.56 cm) | IPS LCD,"AnTuTu Score 72,320","₹7,199"
651,Tecno Camon Slim 4G,MediaTek Helio G200 Ultimate,8 GB RAM | 256 GB Storage,50 MP + 2 MP Rear Camera,32 MP Front Camera,5600 mAh | 60W Ultra Charging,6.78 inches (17.22 cm) | AMOLED,NaN,NaN
4332,Spice Blueberry Blade,NaN,8.7 MB Storage,2 MP Rear Camera,NaN,920 mAh,2.4 inches (6.1 cm) | TFT,NaN,"₹2,999"
1016,Xiaomi 11 Lite NE 5G 8GB RAM,Snapdragon 778G,8 GB RAM | 128 GB Storage,64 MP + 8 MP + 5 MP Rear Camera,20 MP Front Camera,4250 mAh | 33W Fast Charging,6.55 inches (16.64 cm) | AMOLED,AnTuTu Score 0,"₹27,999"
633,Samsung Galaxy A06 5G 128GB,MediaTek Dimensity 6300,4 GB RAM | 128 GB Storage,50 MP + 2 MP Rear Camera,8 MP Front Camera,5000 mAh | 25W Fast Charging,6.7 inches (17.02 cm) | PLS LCD,NaN,"₹11,994"

In [451]:
Price = df['price'].str.replace('₹', '').str.replace(',', '')
df.insert(1, 'Price', value=Price)

In [452]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand_name    4799 non-null   str
 1   Price         4734 non-null   str
 2   processor     3492 non-null   str
 3   storage       4039 non-null   str
 4   back_camera   4674 non-null   str
 5   fron_camera   3618 non-null   str
 6   battery       4782 non-null   str
 7   display       4798 non-null   str
 8   anTuTu_score  1737 non-null   str
 9   price         4734 non-null   str
dtypes: str(10)
memory usage: 375.1 KB

In [453]:
df['Price'] = df['Price'].fillna(0).astype(int)

In [454]:
df.sample(1)

,brand_name,Price,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
3167,Itel Power 430,1399,NaN,NaN,0.3 MP Rear Camera,NaN,2500 mAh,2.4 inches (6.1 cm) | TFT,NaN,"₹1,399"

In [455]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand_name    4799 non-null   str
 1   Price         4800 non-null   int64
 2   processor     3492 non-null   str
 3   storage       4039 non-null   str
 4   back_camera   4674 non-null   str
 5   fron_camera   3618 non-null   str
 6   battery       4782 non-null   str
 7   display       4798 non-null   str
 8   anTuTu_score  1737 non-null   str
 9   price         4734 non-null   str
dtypes: int64(1), str(9)
memory usage: 375.1 KB

In [456]:
df1 = df

In [457]:
df[df['fron_camera'].isnull()]['Price'].describe()

count     1182.000000
mean      2004.302876
std       2927.946826
min          0.000000
25%        944.250000
50%       1229.500000
75%       1850.000000
max      39999.000000
Name: Price, dtype: float64

In [458]:
df[(df['Price'] == 35795)&(df['fron_camera'].isnull())]

,brand_name,Price,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
2995,Sony Ericsson Xperia X10,35795,Snapdragon S1,384 MB RAM | 1 GB Storage,8.1 MP Rear Camera,NaN,1500 mAh,4 inches (10.16 cm) | LCD,NaN,"₹35,795"

In [459]:
df.drop(1174, inplace=True)

In [460]:
df[(df['Price'] == 39999)&(df['fron_camera'].isnull())]

Empty DataFrame
Columns: [brand_name, Price, processor, storage, back_camera, fron_camera, battery, display, anTuTu_score, price]
Index: []

In [461]:
df[df['fron_camera'].isnull()]['Price'].describe()

count     1181.000000
mean      1972.131245
std       2712.142064
min          0.000000
25%        944.000000
50%       1229.000000
75%       1850.000000
max      35795.000000
Name: Price, dtype: float64

In [462]:
df.loc[df['brand_name'] == 'Motorola Razr 50 Ultra', 'display'] = df.loc[df['brand_name'] == 'Motorola Razr 50 Ultra','display'
].str.split(':').str[1]

In [463]:
df[df['brand_name'] == 'Motorola Razr 50 Ultra']

,brand_name,Price,processor,storage,back_camera,fron_camera,battery,display,anTuTu_score,price
737,Motorola Razr 50 Ultra,64811,Snapdragon 8s Gen 3,12 GB RAM | 512 GB Storage,50 MP + 50 MP Rear Camera,32 MP Front Camera,4000 mAh | 45W Turbo Power Charging,"6.9 inches pOLED, 3000 nits, 165 Hz refresh r...","AnTuTu Score 1,408,183","₹64,811"

In [464]:
display_size = df['display'].str.split('|').str[0].str.split(' ').str[0].fillna(0)
df.insert(8, 'display_size', value=display_size)

In [465]:
df['display_size'] = df['display_size'].replace('','0')

In [466]:
df[df['display_size']=='']

Empty DataFrame
Columns: [brand_name, Price, processor, storage, back_camera, fron_camera, battery, display, display_size, anTuTu_score, price]
Index: []

In [467]:
df['display_size'] = df['display_size'].astype(float)

In [468]:
df = df[df['display_size']>3]

In [469]:
df = df[df['storage'].str.contains('RAM')]

In [470]:
df.loc[df['brand_name'] == 'Motorola Razr 70 Plus', 'storage'] = '12 GB RAM | 256 GB Storage'
df.loc[df['brand_name'] == 'Motorola Razr 70 Plus', 'Price'] = 104990

### feature engineering

- we are going to create col such as brand and brand model
- ram and storage from storage col
- primary_rear_camera and no of rear camera from back_camera
- primary_front_camera from fron_camera
- battery_capacity and charging_type from battery col
- display_size and display_type form display col
- exact anTuTu score

In [471]:
df.sample(1)

,brand_name,Price,processor,storage,back_camera,fron_camera,battery,display,display_size,anTuTu_score,price
2013,Itel Zeno 100,8699,Unisoc T7100,3 GB RAM | 64 GB Storage,8 MP Rear Camera,5 MP Front Camera,5000 mAh,6.6 inches (16.76 cm) | IPS LCD,6.6,NaN,"₹8,699"

In [472]:
def len_of_list(l):
    return len(l)

In [473]:
brand = df['brand_name'].str.split(' ').str[0]
df.insert(0, 'brand', value=brand)

In [474]:
ram = df['storage'].str.split('|').str[0].str.split(' ').str[0]
df.insert(4, 'ram', value=ram)

In [475]:
# df['storage'].str.split('|').value_counts()

In [476]:
def storage_to_mb(storage):
    if pd.isna(storage):
        return np.nan
    if 'TB' in storage:
        temp = storage.split()[0]
        return float(temp)*1024
    elif 'MB' in storage:
        temp = storage.split()[0]
        return float(temp)/1024
    elif 'GB' in storage:
        temp = storage.split()[0]
        return float(temp)
    else:
        return np.nan

In [477]:
storage_capacity = df['storage'].str.split('|').str[1]
storage_capacity = storage_capacity.apply(storage_to_mb)
# storage_capacity.value_counts()
df.insert(5, 'storage_capacity', value=storage_capacity)

In [478]:
primary_rear_camera = df['back_camera'].str.split('+').str[0].str.split(' ').str[0]
df.insert(7, 'primary_rear_camera', value=primary_rear_camera)

In [479]:
front_camera = df['fron_camera'].str.split(' ').str[0]
df.insert(10, 'front_camera', value=front_camera)

In [480]:
battery_capacity  = df['battery'].str.split('|').str[0].str.split(' ').str[0]
df.insert(12, 'battery_capacity', value=battery_capacity)

In [481]:
charging_type = df['battery'].str.split('|').str[1]
df.insert(13, 'charging_type', value=charging_type)

In [482]:
display_type = df['display'].str.split('|').str[1]
df.insert(15, 'display_type', value=display_type)

In [483]:
antutu_score = df['anTuTu_score'].str.split(' ').str[2]
df.insert(17, 'antutu_score', value=antutu_score)

In [484]:
df.sample(1)

,brand,brand_name,Price,processor,ram,storage_capacity,storage,primary_rear_camera,back_camera,fron_camera,front_camera,battery,battery_capacity,charging_type,display,display_type,display_size,antutu_score,anTuTu_score,price
2139,Samsung,Samsung Galaxy J2 Core,6400,Samsung Exynos 7 Quad 7570,1,8.0,1 GB RAM | 8 GB Storage,8,8 MP Rear Camera,5 MP Front Camera,5,2600 mAh,2600,NaN,5.0 inches (12.7 cm) | TFT,TFT,5.0,NaN,NaN,"₹6,400"

In [485]:
camera_count = df['back_camera'].str.split('+').apply(len_of_list)
df.insert(8, 'camera_count', value=camera_count)

In [486]:
list_old_col = ['fron_camera', 'battery', 'price', 'anTuTu_score', 'display']

In [487]:
df = df.drop(columns=list_old_col)

In [488]:
df.sample(5)

,brand,brand_name,Price,processor,ram,storage_capacity,storage,primary_rear_camera,camera_count,back_camera,front_camera,battery_capacity,charging_type,display_type,display_size,antutu_score
800,POCO,POCO X8 5G 8GB RAM,32999,Snapdragon 6s Gen 4,8,128.0,8 GB RAM | 128 GB Storage,50,2,50 MP + 2 MP Rear Camera,16,9000,67W Hyper Charging,AMOLED,6.83,NaN
4075,Apple,Apple iPhone 6s Plus 128GB,70000,Apple A9,2,128.0,2 GB RAM | 128 GB Storage,12,1,12 MP Rear Camera,5,2750,NaN,IPS LCD,5.50,NaN
3517,Moto,Moto G8 Power Lite,9999,MediaTek Helio P35,4,64.0,4 GB RAM | 64 GB Storage,16,3,16 MP + 2 MP + 2 MP Rear Camera,8,5000,10W,IPS LCD,6.50,NaN
287,OnePlus,OnePlus 9,24490,Snapdragon 888,8,128.0,8 GB RAM | 128 GB Storage,48,3,48 MP + 50 MP + 2 MP Rear Camera,16,4500,65W Warp Charging,Fluid AMOLED,6.55,"721,282"
3661,Kenxinda,Kenxinda W55,4299,Spreadtrum SC9832A,1,8.0,1 GB RAM | 8 GB Storage,8,1,8 MP Rear Camera,5,2500,NaN,IPS LCD,5.50,NaN

In [489]:
df.info()

<class 'pandas.DataFrame'>
Index: 3611 entries, 0 to 4782
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                3610 non-null   object
 1   brand_name           3610 non-null   str
 2   Price                3611 non-null   int64
 3   processor            3448 non-null   str
 4   ram                  3611 non-null   object
 5   storage_capacity     3600 non-null   float64
 6   storage              3611 non-null   str
 7   primary_rear_camera  3611 non-null   object
 8   camera_count         3611 non-null   int64
 9   back_camera          3611 non-null   str
 10  front_camera         3574 non-null   object
 11  battery_capacity     3611 non-null   object
 12  charging_type        2452 non-null   object
 13  display_type         3598 non-null   object
 14  display_size         3611 non-null   float64
 15  antutu_score         1735 non-null   object
dtypes: float64(2), int64(2), object(8), str(4)
memory usage: 479.6+ KB

In [490]:
df.rename(columns={'brand_name':'model'}, inplace=True)

In [491]:
df['ram'] = df['ram'].str.replace('GB','')
df['ram'] = df['ram'].astype(float)

In [492]:
df['primary_rear_camera'] = df['primary_rear_camera'].str.replace("MP","")
df['primary_rear_camera'] = df['primary_rear_camera'].astype(float)

df['front_camera'] = df['front_camera'].str.replace("MP","")
df['front_camera'] = df['front_camera'].astype(float)

In [493]:
df['battery_capacity'] = df['battery_capacity'].str.replace("mAh","")
df['battery_capacity'] = df['battery_capacity'].astype(int)

In [494]:
df['antutu_score'] = df['antutu_score'].str.replace(',', '', regex=True)
df['antutu_score'] = df['antutu_score'].astype('Int64')

In [495]:
df.info()

<class 'pandas.DataFrame'>
Index: 3611 entries, 0 to 4782
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                3610 non-null   object
 1   model                3610 non-null   str
 2   Price                3611 non-null   int64
 3   processor            3448 non-null   str
 4   ram                  3611 non-null   float64
 5   storage_capacity     3600 non-null   float64
 6   storage              3611 non-null   str
 7   primary_rear_camera  3611 non-null   float64
 8   camera_count         3611 non-null   int64
 9   back_camera          3611 non-null   str
 10  front_camera         3574 non-null   float64
 11  battery_capacity     3611 non-null   int64
 12  charging_type        2452 non-null   object
 13  display_type         3598 non-null   object
 14  display_size         3611 non-null   float64
 15  antutu_score         1735 non-null   Int64
dtypes: Int64(1), float64(5), int64(3), object(3), str(4)
memory usage: 483.1+ KB

In [496]:
df.drop(index=[3034, 4278, 4290, 4306, 4494], inplace=True)
df.drop(index=[2515], inplace=True)

In [497]:
temp_df = df[(df['ram']>18) & (df['storage_capacity']>16)][['ram', 'storage_capacity']]/1024

In [498]:
df.loc[temp_df.index, ['ram', 'storage_capacity']] = temp_df.values

In [499]:
processor_brand = df['processor'].str.split(' ').str[0]
df.insert(3, 'processor_brand', processor_brand)

In [500]:
df['charging_type'].value_counts()

charging_type
18W Fast Charging              249
10W                            212
25W Fast Charging              186
15W Fast Charging              137
33W Fast Charging              130
                              ...
33W Rapid Charging               1
15W Turbo Charging               1
7.5W Fast Charging               1
33W Super Charging               1
45W SuperVOOC fast charging      1
Name: count, Length: 146, dtype: int64

In [501]:
def set_tier(price):
    if price<15000:
        return "Budget Tier"
    elif price < 30000:
        return "Mid Tier"
    elif price < 45000:
        return "High Tier"
    else:
        return "Ultra-Premium Tier"

In [502]:
price_tier = df['Price'].apply(set_tier)
df.insert(3, "price_tier", price_tier)

In [503]:
temp_df = df[df['Price']==0]
df.drop(index=temp_df.index, inplace=True)

In [504]:
df[df['brand'].isnull()]

,brand,model,Price,price_tier,processor_brand,processor,ram,storage_capacity,storage,primary_rear_camera,camera_count,back_camera,front_camera,battery_capacity,charging_type,display_type,display_size,antutu_score
1175,NaN,NaN,121999,Ultra-Premium Tier,Samsung,Samsung Exynos 2500,12.0,512.0,12 GB RAM | 512 GB Storage,50.0,2,50 MP + 12 MP Rear Camera,10.0,4300,25W Fast Charging,Dynamic AMOLED 2x (Main Display),6.9,<NA>

In [505]:
df.loc[1175, ['brand', 'model']] = ['Samsung', 'Samsung Galaxy Z Flip7']

In [506]:
df[df['brand'].isnull()]

Empty DataFrame
Columns: [brand, model, Price, price_tier, processor_brand, processor, ram, storage_capacity, storage, primary_rear_camera, camera_count, back_camera, front_camera, battery_capacity, charging_type, display_type, display_size, antutu_score]
Index: []

In [507]:
df['display_type'].value_counts()

display_type
IPS LCD                             1592
AMOLED                               631
LCD                                  247
Super AMOLED                         229
TFT                                  141
OLED                                  76
Super Retina XDR                      76
Dynamic AMOLED 2x                     59
PLS LCD                               52
P-OLED                                44
Flexible AMOLED                       43
Fluid AMOLED                          42
PLS TFT LCD                           39
LTPO AMOLED                           38
Super AMOLED Plus                     28
Dynamic AMOLED 2x (Main Display)      25
LTPS AMOLED                           18
Super Retina XDR OLED                 14
LTPO OLED                             13
AMOLED (Main Display)                 13
ProXDR LTPO                           11
Extreme AMOLED                         9
LTPS LCD                               8
Super Fluid AMOLED                     7
Optic AMOLED                           6
Dynamic AMOLED (Main Display)          5
IPS LCD (Main Display)                 5
LTPS OLED                              4
LTPO AMOLED (Main Display)             4
P-OLED (Main Display)                  4
S-LCD                                  4
Swift AMOLED                           3
Flow AMOLED                            3
Hyper Glow AMOLED                      3
Dynamic AMOLED                         3
TFT LCD                                3
IPS LED                                3
Sunburst AMOLED                        2
TFT IPS                                2
OLED (Main Display)                    2
Flat OLED                              2
LTPS IPS                               2
LTPO Flexi-fluid AMOLED                2
S-LCD 5                                2
S-LCD 3                                2
S-LCD 2                                2
LTPO OLED (Main Display)               1
S-LCD 6                                1
Super PLS LCD                          1
S-LCD 5 (Main Display)                 1
True HD IPS Plus LCD                   1
TFD                                    1
Name: count, dtype: int64

In [508]:
lcd_list = ['IPS LCD', 'LCD', 'LTPS LCD', 'IPS LED', 'TFT IPS', 'LTPS IPS', 'PLS LCD', 'PLS TFT LCD', 'Super PLS LCD', 'S-LCD', 'True HD IPS Plus LCD', 'IPS LCD (Main Display)', 'S-LCD 5', 'S-LCD 3', 'S-LCD 2', 'S-LCD 6', 'S-LCD 5 (Main Display)']

tft_list = ['TFT', 'TFT LCD', 'TFD']

poled_list = ['P-OLED', 'P-OLED (Main Display)', 'LTPO P-OLED']

amoled_list = ['AMOLED', 'Super AMOLED', 'Dynamic AMOLED 2x', 'Fluid AMOLED', 'LTPO AMOLED', 'Flexible AMOLED', 'Super AMOLED Plus', 'LTPS AMOLED', 'Optic AMOLED', 'Extreme AMOLED', 'Dynamic AMOLED 2x (Main Display)', 'AMOLED (Main Display)', 'Super Fluid AMOLED', 'Dynamic AMOLED (Main Display)', 'LTPO AMOLED (Main Display)', 'Swift AMOLED', 'Flow AMOLED', 'Hyper Glow AMOLED', 'Dynamic AMOLED', 'Sunburst AMOLED', 'LTPO Flexi-fluid AMOLED', ]

oled_list = ['OLED', 'Super Retina XDR', 'Super Retina XDR OLED', 'LTPO OLED', 'Flat OLED', 'LTPS OLED', 'ProXDR LTPO', 'OLED (Main Display)','LTPO OLED (Main Display)']

In [509]:
df['display_type'] = df['display_type'].str.strip().replace(lcd_list, 'LCD')
df['display_type'] = df['display_type'].str.strip().replace(tft_list, 'TFT')
df['display_type'] = df['display_type'].str.strip().replace(poled_list, 'POLED')
df['display_type'] = df['display_type'].str.strip().replace(amoled_list, 'AMOLED')
df['display_type'] = df['display_type'].str.strip().replace(oled_list, 'OLED')

In [510]:
df['display_type'].isin(amoled_list).sum()

np.int64(1173)

In [511]:
df.head(5)

,brand,model,Price,price_tier,processor_brand,processor,ram,storage_capacity,storage,primary_rear_camera,camera_count,back_camera,front_camera,battery_capacity,charging_type,display_type,display_size,antutu_score
0,vivo,vivo S2 5G,39490,High Tier,MediaTek,MediaTek Dimensity 7360 Turbo,8.0,128.0,8 GB RAM | 128 GB Storage,50.0,2,50 MP + 2 MP Rear Camera,32.0,7050,44W Flash Charging,AMOLED,6.83,956029
1,Motorola,Motorola Edge 70 Fusion,28990,Mid Tier,Snapdragon,Snapdragon 7s Gen 4,8.0,128.0,8 GB RAM | 128 GB Storage,50.0,2,50 MP + 13 MP Rear Camera,32.0,7000,68W Turbo Power Charging,AMOLED,6.80,1149292
3,iQOO,iQOO Z11 5G,34999,High Tier,MediaTek,MediaTek Dimensity 7500 turbo,6.0,128.0,6 GB RAM | 128 GB Storage,50.0,2,50 MP + 8 MP Rear Camera,32.0,7050,44W Flash Charging,AMOLED,6.83,1099769
4,Xiaomi,Xiaomi Redmi Note 17 5G,27999,Mid Tier,Snapdragon,Snapdragon 4 Gen 4,6.0,128.0,6 GB RAM | 128 GB Storage,50.0,2,50 MP + 2 MP Rear Camera,8.0,8000,45W Fast Charging,OLED,6.99,626958
7,vivo,vivo T4X,16999,Mid Tier,MediaTek,MediaTek Dimensity 7300,6.0,128.0,6 GB RAM | 128 GB Storage,50.0,2,50 MP + 2 MP Rear Camera,8.0,6500,44W Flash Charging,LCD,6.72,685052

In [512]:
df['display_type'].value_counts()

display_type
LCD       1964
AMOLED    1173
OLED       199
TFT        145
POLED       48
Name: count, dtype: int64

In [513]:
df.info()

<class 'pandas.DataFrame'>
Index: 3540 entries, 0 to 4782
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                3540 non-null   object
 1   model                3540 non-null   str
 2   Price                3540 non-null   int64
 3   price_tier           3540 non-null   str
 4   processor_brand      3382 non-null   object
 5   processor            3382 non-null   str
 6   ram                  3540 non-null   float64
 7   storage_capacity     3530 non-null   float64
 8   storage              3540 non-null   str
 9   primary_rear_camera  3540 non-null   float64
 10  camera_count         3540 non-null   int64
 11  back_camera          3540 non-null   str
 12  front_camera         3510 non-null   float64
 13  battery_capacity     3540 non-null   int64
 14  charging_type        2393 non-null   object
 15  display_type         3529 non-null   object
 16  display_size         3540 non-null   float64
 17  antutu_score         1734 non-null   Int64
dtypes: Int64(1), float64(5), int64(3), object(4), str(5)
memory usage: 658.0+ KB

In [514]:
col_to_drop = ['storage', 'back_camera']
df.drop(columns=col_to_drop, inplace=True)

In [515]:
df.info()

<class 'pandas.DataFrame'>
Index: 3540 entries, 0 to 4782
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   brand                3540 non-null   object
 1   model                3540 non-null   str
 2   Price                3540 non-null   int64
 3   price_tier           3540 non-null   str
 4   processor_brand      3382 non-null   object
 5   processor            3382 non-null   str
 6   ram                  3540 non-null   float64
 7   storage_capacity     3530 non-null   float64
 8   primary_rear_camera  3540 non-null   float64
 9   camera_count         3540 non-null   int64
 10  front_camera         3510 non-null   float64
 11  battery_capacity     3540 non-null   int64
 12  charging_type        2393 non-null   object
 13  display_type         3529 non-null   object
 14  display_size         3540 non-null   float64
 15  antutu_score         1734 non-null   Int64
dtypes: Int64(1), float64(5), int64(3), object(4), str(3)
memory usage: 602.7+ KB

In [516]:
df.head(8)

,brand,model,Price,price_tier,processor_brand,processor,ram,storage_capacity,primary_rear_camera,camera_count,front_camera,battery_capacity,charging_type,display_type,display_size,antutu_score
0,vivo,vivo S2 5G,39490,High Tier,MediaTek,MediaTek Dimensity 7360 Turbo,8.0,128.0,50.0,2,32.0,7050,44W Flash Charging,AMOLED,6.83,956029
1,Motorola,Motorola Edge 70 Fusion,28990,Mid Tier,Snapdragon,Snapdragon 7s Gen 4,8.0,128.0,50.0,2,32.0,7000,68W Turbo Power Charging,AMOLED,6.80,1149292
3,iQOO,iQOO Z11 5G,34999,High Tier,MediaTek,MediaTek Dimensity 7500 turbo,6.0,128.0,50.0,2,32.0,7050,44W Flash Charging,AMOLED,6.83,1099769
4,Xiaomi,Xiaomi Redmi Note 17 5G,27999,Mid Tier,Snapdragon,Snapdragon 4 Gen 4,6.0,128.0,50.0,2,8.0,8000,45W Fast Charging,OLED,6.99,626958
7,vivo,vivo T4X,16999,Mid Tier,MediaTek,MediaTek Dimensity 7300,6.0,128.0,50.0,2,8.0,6500,44W Flash Charging,LCD,6.72,685052
8,vivo,vivo T5x,27299,Mid Tier,MediaTek,MediaTek Dimensity 7400 Turbo,6.0,128.0,50.0,2,32.0,7200,44W Flash Charging,LCD,6.76,<NA>
9,Motorola,Motorola Edge 60 Fusion,20900,Mid Tier,MediaTek,MediaTek Dimensity 7400,8.0,128.0,50.0,2,32.0,5500,68W Turbo Power Charging,POLED,6.67,692185
11,Samsung,Samsung Galaxy F70 Pro 5G,26337,Mid Tier,Snapdragon,Snapdragon 6 Gen 3,6.0,128.0,50.0,3,12.0,6000,45W Fast Charging,AMOLED,6.70,<NA>

In [517]:
# df['storage_capacity'].value_counts()
df['charging_type'].isnull().sum()

np.int64(1147)

In [518]:
def classify_charging_type(charging):
    if pd.isna(charging):
        return 0
    else:
        return 1

In [519]:
is_fast_charging_available = df['charging_type'].apply(classify_charging_type)
df.insert(12, 'is_fast_chargig', is_fast_charging_available)

In [520]:
df['charging_type'] = df['charging_type'].str.strip().str.split(' ').str[0].str.split('W').str[0].astype(float)

In [521]:
df.sample(10)

,brand,model,Price,price_tier,processor_brand,processor,ram,storage_capacity,primary_rear_camera,camera_count,front_camera,battery_capacity,is_fast_chargig,charging_type,display_type,display_size,antutu_score
638,POCO,POCO M8 Power 5G 8GB RAM,26880,Mid Tier,Snapdragon,Snapdragon 4 Gen 4,8.0,128.0,50.0,2,8.0,8000,1,45.0,AMOLED,6.830,619773
1463,Tecno,Tecno Spark Go 5G,10999,Budget Tier,MediaTek,MediaTek Dimensity 6400,4.0,128.0,50.0,1,5.0,6000,1,18.0,LCD,6.745,418472
4169,XOLO,XOLO Play 8X-1200,20999,Mid Tier,MediaTek,MediaTek MT6592T,2.0,32.0,13.0,1,5.0,2300,0,NaN,LCD,5.000,<NA>
4128,Lava,Lava Iris X8,6349,Budget Tier,MediaTek,MediaTek MT6592M,2.0,16.0,8.0,1,3.0,2500,0,NaN,LCD,5.000,<NA>
464,Xiaomi,Xiaomi Redmi A7 4G,12299,Budget Tier,Unisoc,Unisoc T7250,3.0,64.0,13.0,1,8.0,5200,1,15.0,LCD,6.880,<NA>
340,Xiaomi,Xiaomi Redmi Turbo 5 12GB 256GB RAM,46999,Ultra-Premium Tier,MediaTek,MediaTek Dimensity 8500 Ultra,12.0,256.0,50.0,2,20.0,7540,1,100.0,AMOLED,6.590,<NA>
344,Wobble,Wobble One,23899,Mid Tier,MediaTek,MediaTek Dimensity 7400,8.0,128.0,50.0,3,50.0,5000,1,33.0,AMOLED,6.670,979430
3012,Lava,Lava Shark,7355,Budget Tier,Unisoc,Unisoc T606,4.0,64.0,50.0,1,8.0,5000,1,18.0,LCD,6.670,<NA>
4755,Samsung,Samsung Galaxy M15 Prime Edition 6GB RAM,16999,Mid Tier,MediaTek,MediaTek Dimensity 6100 Plus,6.0,128.0,50.0,3,13.0,6000,1,25.0,AMOLED,6.600,<NA>
37,vivo,vivo X200T,59999,Ultra-Premium Tier,MediaTek,MediaTek Dimensity 9400 Plus,12.0,256.0,50.0,3,32.0,6200,1,90.0,AMOLED,6.670,2821319

In [522]:
df.to_csv("cleaned_df.csv", index=False)